#!/usr/bin/env python3
"""IMMUTABLE unittest for the aiter FlyDSL fused MoE stage-2 op (Kimi-K3, TP=8, gfx950).

OP (the whole rebindable fused seam -- BOTH hot kernels run inside this ONE call):
    aiter.ops.flydsl.moe_kernels:flydsl_moe_stage2
      -> mfma_moe2_afp8_wfp4_bf16_cshuffle_t64x256x128_..._acc0   (down-proj GEMM)  ~7.1% GPU time
      -> moe_reduction_kernel_plain_bf16_topk16_md3584            (top-16 combine)  ~3.2% GPU time
    live seam: AiterRunnerCore.run -> aiter.fused_moe:fused_moe -> _flydsl_stage2_wrapper
               -> aiter.ops.flydsl.flydsl_moe_stage2
    The byte-reduction lever (fusing the top-16 reduction into the cshuffle epilogue) is entirely
    inside this call, so the call -- not a single kernel -- is the timed unit.

BASELINE  = the FROZEN production package copy in baseline_src/flydsl/ (never kernel_src/).
CANDIDATE = whatever is currently in kernel_src/flydsl/.
speedup   = baseline_ms / candidate_ms, in ANY language/backend (flydsl, aiter, triton, ...).

ROUTING IS REAL: sorted_token_ids / sorted_expert_ids / num_valid_ids / sorted_weights / topk_ids in
reference_io.pt were captured from the LIVE TP=8 server on the served workload (or rebuilt from the
LIVE topk_ids with the real aiter moe_sorting); it is never synthesized. The value-INDEPENDENT heavy
operands (fp8 activations, packed mxfp4 w2 + scales) are re-synthesized deterministically at the
captured dims/dtypes, and the golden output is the frozen baseline's own output on them.

DO NOT EDIT THIS FILE, harness_lib.py, reference_io.pt, meta.json or baseline_src/ during optimization.
"""
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Load the vendored shared harness BEFORE dropping HERE from sys.path / importing torch
# (this file is named unittest.py and would otherwise shadow the stdlib module).
_spec = importlib.util.spec_from_file_location("harness_lib", os.path.join(HERE, "harness_lib.py"))
h = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(h)

sys.path = [p for p in sys.path if os.path.abspath(p or ".") != HERE]

import torch  # noqa: E402

with open(os.path.join(HERE, "meta.json")) as _fh:
    META = json.load(_fh)

REGIME = META["regime"]
GEO = META["geometry"]
TOL = float(META.get("tol", 2e-2))
DEV = "cuda" if torch.cuda.is_available() else "cpu"

E = int(GEO["num_experts"])             # 896 (per-rank expert count)
TOPK = int(GEO["topk"])                 # 16
MODEL_DIM = int(GEO["model_dim"])       # 3584 (routed-expert output dim)
INTER_DIM = int(GEO["inter_dim"])       # 384  (= moe_intermediate / TP8)


# --------------------------------------------------------------------------- kernel binding

def _load_frozen_capture(torch, path, **kwargs):
    import importlib.util
    from pathlib import Path
    helper = Path(__file__).resolve().with_name("task_contract.py")
    spec = importlib.util.spec_from_file_location("_frozen_capture_loader", helper)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.verified_torch_load(torch, path, **kwargs)


def _load_pkg(root, name, *, frozen=False):
    """Load the exact MoE dependency closure without package-wide reexports."""
    spec = importlib.util.spec_from_file_location(
        "_task_flydsl_package", os.path.join(HERE, "flydsl_package.py"))
    helper = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(helper)
    manifest = os.path.join(HERE, "dependency_manifest.json") if frozen else None
    return helper.load_moe_package(root, name, frozen_manifest=manifest)


_BASELINE_PKG = _load_pkg(os.path.join(HERE, "baseline_src", "flydsl"), "geak_frozen_flydsl", frozen=True)
_CANDIDATE_PKG = _load_pkg(os.path.join(HERE, "kernel_src", "flydsl"), "geak_candidate_flydsl")
ENTRY = META["entry_attr"]                        # "flydsl_moe_stage2"
BASELINE_FN = getattr(_BASELINE_PKG, ENTRY)
CANDIDATE_FN = getattr(_CANDIDATE_PKG, ENTRY)


# --------------------------------------------------------------------------- oracle (REAL routing)
_ORACLE = _load_frozen_capture(torch, os.path.join(HERE, "reference_io.pt"), map_location="cpu", weights_only=False)
ROUTING = {c["spec"]["sig"]: c["routing"] for c in _ORACLE["cases"]}


def _as(dt_name, u8):
    """Reinterpret a byte tensor as the live storage dtype (fp8 e4m3 / e8m0, packed fp4x2)."""
    dt = getattr(torch, dt_name.split(".")[-1], None)
    if dt is None:
        raise TypeError(f"runtime is missing captured storage dtype {dt_name}")
    return u8.view(dt)


def _rand_bytes(shape, lo, hi, gen):
    return torch.randint(lo, hi, tuple(shape), dtype=torch.uint8, device=DEV, generator=gen)


def build_inputs(spec, gen=None):
    """Rebuild ONE case's operands in the LIVE dtypes/layout/launch-variant.

    REAL (captured from the live TP=8 server, never synthesized): sorted_token_ids,
    sorted_expert_ids, num_valid_ids, sorted_weights (+ topk_ids/expert_mask when the live call
    passes them) -- i.e. the entire routing / expert-imbalance signal that sets this op's cost.
    SYNTHESIZED deterministically (value-independent for both cost and the correctness contract):
      inter_states : (token_num, topk, inter_dim)  float8_e4m3fn      stage-1 activations
      w2           : (E, model_dim, inter_dim//2)  float4_e2m1fn_x2   packed mxfp4 down-proj
      w2_scale / a2_scale : float8_e8m0fnu mx group scales, at the captured shapes
    """
    sig = spec["sig"]
    if gen is None:
        gen = torch.Generator(device=DEV).manual_seed(int(spec["seed"]))
    tok = int(spec["token_num"])
    routing = {k: v.to(DEV) for k, v in ROUTING[sig].items()}

    # fp8 e4m3 activations. Byte-level synthesis with a REALISTIC dynamic range: exponent field
    # 6..8 (|x| in [0.5, 4)) plus a random sign, i.e. the post-normalization scale a served
    # stage-1 activation actually has. Sampling the full e4m3 exponent range instead would span
    # 2^20 in magnitude and manufacture catastrophic cancellation inside the top-16 combine --
    # which matters because the decode launch variant reduces with bf16 ATOMICS, whose summation
    # order (and therefore rounding) is not reproducible run to run.
    a_u8 = torch.bitwise_or(_rand_bytes(spec["a_shape"], 0x30, 0x48, gen),
                            _rand_bytes(spec["a_shape"], 0, 2, gen) << 7)
    inter_states = _as(spec["a_dtype_t"], a_u8)
    w2 = _as(spec["w2_dtype_t"], _rand_bytes(spec["w2_bytes_shape"], 0, 256, gen))
    if list(w2.shape) != list(spec["w2_shape"]):
        w2 = w2.view(*spec["w2_shape"])
    # e8m0 mx group scales around 2^0 (byte 127) -> well-conditioned magnitudes
    w2_scale = _as(spec["scale_dtype_t"], _rand_bytes(spec["w2_scale_shape"], 126, 130, gen))
    a2_scale = None
    if spec.get("a2_scale_shape"):
        a2_scale = _as(spec["scale_dtype_t"], _rand_bytes(spec["a2_scale_shape"], 126, 130, gen))
    return {"inter_states": inter_states, "w2": w2, "w2_scale": w2_scale, "a2_scale": a2_scale,
            "routing": routing, "token_num": tok, "sig": sig,
            "kwargs": dict(spec["kwargs"]), "alloc_out": bool(spec.get("caller_allocates_out", True))}


def fingerprint(args):
    return [int(args["inter_states"].reshape(-1)[:64].view(torch.uint8).sum()),
            int(args["w2"].reshape(-1)[:4096].view(torch.uint8).sum()),
            int(args["routing"]["sorted_token_ids"][:4096].sum()),
            int(args["routing"]["num_valid_ids"][0])]


def _invoke(fn, args, out=None, zero=True):
    """Call the seam EXACTLY as the live aiter dispatch does (kwargs captured at the seam).

    NOTE on `out`: in the live atomic variant the caller hands in the ZEROED moe_buf and stage-2
    accumulates into it; in the reduce variant stage-2 writes a private [T*topk*model_dim] target
    and the fused top-16 reduction fills `out`. Both are reproduced here (zeroing when the live
    dispatch zeroes)."""
    r = args["routing"]
    kw = args["kwargs"]
    if out is None and args.get("alloc_out", True):
        out = torch.zeros((int(args["token_num"]), MODEL_DIM), dtype=torch.bfloat16, device=DEV)
    elif out is not None and zero and kw.get("mode", "atomic") != "reduce":
        out.zero_()
    return fn(args["inter_states"], args["w2"], r["sorted_token_ids"], r["sorted_expert_ids"],
              r["num_valid_ids"], out, TOPK,
              w2_scale=args["w2_scale"], a2_scale=args["a2_scale"],
              sorted_weights=r.get("sorted_weights"),
              expert_mask=r.get("expert_mask"),
              topk_ids=(r.get("topk_ids") if r.get("expert_mask") is not None else None),
              **kw)


def make_call(fn):
    """launcher contract: call(args) -> FRESH out (never a persistent/static buffer)."""
    def call(args):
        return _invoke(fn, args, None)
    return call


baseline_call = make_call(BASELINE_FN)
current_call = make_call(CANDIDATE_FN)


# --------------------------------------------------------------------------- graph-replay bundle
def build_replay(cases_specs):
    """Deployment-context replay: capture ONE graph on the largest decode batch, then replay the
    SMALLER boundary batch through the SAME static buffers -- exactly how the server runs a padded
    decode step (num_valid_ids shrinks, the padded rows are don't-care). A candidate that sizes a
    workspace to the capture shape, or that walks past num_valid_ids, faults only here.

    The per-case reference is produced by the FROZEN baseline in the SAME static configuration
    (same padded token_num and same launch variant as the captured graph), never with the case's own
    eager variant -- otherwise a padded replay would be compared against an unpadded launch.
    """
    specs = sorted(cases_specs, key=lambda s: int(s["token_num"]), reverse=True)
    big = build_inputs(specs[0])
    tok_max = int(specs[0]["token_num"])
    r_big = big["routing"]

    st_a = torch.zeros_like(big["inter_states"])
    st_sti = torch.zeros_like(r_big["sorted_token_ids"])
    st_sei = torch.zeros_like(r_big["sorted_expert_ids"])
    st_nvi = torch.zeros_like(r_big["num_valid_ids"])
    st_sw = (torch.zeros_like(r_big["sorted_weights"])
             if r_big.get("sorted_weights") is not None else None)
    st_out = torch.zeros((tok_max, MODEL_DIM), dtype=torch.bfloat16, device=DEV)
    st_routing = {"sorted_token_ids": st_sti, "sorted_expert_ids": st_sei, "num_valid_ids": st_nvi}
    if st_sw is not None:
        st_routing["sorted_weights"] = st_sw
    st_args = {"inter_states": st_a, "w2": big["w2"], "w2_scale": big["w2_scale"],
               "a2_scale": big["a2_scale"], "routing": st_routing, "token_num": tok_max,
               "kwargs": dict(big["kwargs"]), "alloc_out": False}
    cur = {"tok": tok_max}

    def fill(case):
        a = case["args"]
        t = int(a["token_num"])
        cur["tok"] = t
        st_a.zero_()
        st_a[:t].copy_(a["inter_states"])
        r = a["routing"]
        # padded slots carry the sorter's own invalid marker (slot index == topk), like the server
        st_sti.fill_(TOPK << 24)
        st_sei.zero_()
        st_sti[: r["sorted_token_ids"].numel()].copy_(r["sorted_token_ids"])
        st_sei[: r["sorted_expert_ids"].numel()].copy_(r["sorted_expert_ids"])
        st_nvi.copy_(r["num_valid_ids"])
        if st_sw is not None and r.get("sorted_weights") is not None:
            st_sw.zero_()
            st_sw[: r["sorted_weights"].numel()].copy_(r["sorted_weights"])

    def run():
        _invoke(CANDIDATE_FN, st_args, st_out)

    def read_out():
        return st_out[: cur["tok"]]

    cases = []
    for sp in specs:
        a = build_inputs(sp)
        a["w2"], a["w2_scale"], a["a2_scale"] = big["w2"], big["w2_scale"], big["a2_scale"]
        if (int(a["routing"]["sorted_token_ids"].numel()) > st_sti.numel()
                or int(a["routing"]["sorted_expert_ids"].numel()) > st_sei.numel()):
            continue                              # cannot be padded into this capture's buffers
        case = {"args": a, "sig": sp["sig"], "_tok": int(sp["token_num"])}
        fill(case)                                # reference in the STATIC (padded) configuration
        ref_out = torch.zeros_like(st_out)
        _invoke(BASELINE_FN, st_args, ref_out)
        case["ref"] = ref_out[: int(sp["token_num"])].clone()
        cases.append(case)
        del ref_out

    return {"fill": fill, "run": run, "read_out": read_out, "cases": cases, "capture_idx": 0}


# --------------------------------------------------------------------------- oracle / timing sets
def load_oracle():
    eager_cases, bad_fp = [], []
    for rec in _ORACLE["cases"]:
        args = build_inputs(rec["spec"])
        fp = fingerprint(args)
        if fp != rec["fingerprint"]:
            bad_fp.append((rec["spec"]["sig"], fp, rec["fingerprint"]))
        eager_cases.append({"args": args, "ref": rec["ref"].to(DEV), "sig": rec["spec"]["sig"]})
    return eager_cases, bad_fp


def timing_cases():
    """One case per meta.workload.cases[] entry (own dims + regime), else every frozen case spec."""
    wl = (META.get("workload") or {}).get("cases") or []
    by_sig = {s["sig"]: s for s in META["case_specs"]}
    out = []
    for c in wl:
        spec = c.get("case_spec") or by_sig.get(c.get("name"))
        if spec:
            out.append({"spec": spec, "regime": c.get("regime") or spec.get("regime", "prefill"),
                        "m": c.get("m") or int(spec["token_num"])})
    if not out:
        for spec in META["case_specs"]:
            out.append({"spec": spec, "regime": spec.get("regime", "prefill"),
                        "m": int(spec["token_num"])})
    return out


def time_bucket(entry, warmup, repeats):
    graph = h.deployment_graph_mode(REGIME)
    base = h.compiled_op(BASELINE_FN, REGIME)
    cand = h.compiled_op(CANDIDATE_FN, REGIME)
    args = build_inputs(entry["spec"])
    # Persistent `out` + zero=False: the live dispatch gets its zeroed moe_buf from moe_sorting,
    # OUTSIDE this seam, so the memset must not be folded into either leg's timing.
    out = torch.zeros((int(args["token_num"]), MODEL_DIM), dtype=torch.bfloat16, device=DEV)
    b = h.time_op(lambda: _invoke(base, args, out, zero=False), warmup, repeats, 1, graph, detail=True)
    c = h.time_op(lambda: _invoke(cand, args, out, zero=False), warmup, repeats, 1, graph, detail=True)
    # Decode buckets pay the launch/graph fixed cost every step, x OSL-amplified: score the
    # launch-INCLUSIVE (wall) sample there; prefill chunks are device-bound.
    pick = ((lambda d: (d or {}).get("wall_ms")) if entry["regime"] == "decode"
            else (lambda d: (d or {}).get("ms")))
    row = {"sig": entry["spec"]["sig"], "regime": entry["regime"], "m": entry["m"],
           "baseline_ms": pick(b), "optimized_ms": pick(c),
           "baseline_device_ms": (b or {}).get("ms"), "optimized_device_ms": (c or {}).get("ms"),
           "timer": (b or {}).get("timer")}
    del args, out
    torch.cuda.empty_cache()
    return row


# --------------------------------------------------------------------------- main
def main():
    argv = sys.argv[1:]
    warmup, repeats = 5, 20
    if "--time-bucket" in argv:                       # fresh-subprocess per-bucket re-measurement
        sig = argv[argv.index("--time-bucket") + 1]
        for e in timing_cases():
            if e["spec"]["sig"] == sig:
                print("GEAK_BUCKET " + json.dumps(time_bucket(e, warmup, repeats)))
                return 0
        print(f"unknown bucket {sig}", file=sys.stderr)
        return 2

    if not torch.cuda.is_available():
        print("ENV: no CUDA/HIP device", file=sys.stderr)
        return 2

    eager_cases, bad_fp = load_oracle()
    if bad_fp:
        print("ENV: deterministic input rebuild MISMATCHED the frozen oracle fingerprint "
              f"(torch/GPU RNG drift): {bad_fp}", file=sys.stderr)
        return 2

    replay = build_replay(META["replay_specs"])
    try:
        ok, report = h.run_correctness(
            REGIME, eager_cases=eager_cases,
            baseline_call=baseline_call, current_call=current_call,
            random_shapes=[{"sig": s["sig"],
                            "make_inputs": (lambda sp: (lambda rng: build_inputs(sp, rng)))(s)}
                           for s in META["case_specs"]],
            tol=TOL, draws=int(META.get("random_draws", 3)), replay=replay)
    except h.HarnessIncompleteError:
        return 3                                       # 3 = regenerate UT (sentinel already printed)

    for leg, rows in report.items():
        for r in rows:
            print(f"[{leg}] {r.get('case')}: correct={r.get('correct')} "
                  f"max_rel_err={r.get('max_rel_err')} {r.get('note','')}")

    seq_ok, seq_rows = h.check_correct_sequence(
        current_call, [eager_cases[i] for i in META.get("call_sequence_idx", [0, 1, 0])], TOL)
    for r in seq_rows:
        print(f"[sequence] {r.get('case')}: correct={r.get('correct')} max_rel_err={r.get('max_rel_err')}")
    ok = ok and seq_ok

    del replay, eager_cases
    torch.cuda.empty_cache()

    per_case = []
    for e in timing_cases():
        row = time_bucket(e, warmup, repeats)
        per_case.append(row)
        print(f"[timing] {row['sig']} m={row['m']} regime={row['regime']} "
              f"baseline_ms={row['baseline_ms']} optimized_ms={row['optimized_ms']} "
              f"(device {row['baseline_device_ms']} / {row['optimized_device_ms']}, timer={row['timer']})")

    res = h.serving_weighted_speedup(per_case, META)
    print("GEAK_PER_CASE " + json.dumps(res["per_case"]))
    print(f"GEAK_GEOMEAN_SPEEDUP {res['geomean']}")
    print(f"GEAK_WEIGHTED_SPEEDUP {res['weighted']}")
    if res["weighted"] is None:
        print(f"GEAK_WEIGHT_UNTRUSTED {res['reason']}")
    print("GEAK_CORRECT " + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
