#!/usr/bin/env python3
"""IMMUTABLE unittest for the aiter FlyDSL fused MoE stage-1 op (Kimi-K3, TP=8, gfx950).

OP (the rebindable fused seam):
    aiter.ops.flydsl.moe_kernels:flydsl_moe_stage1
      -> flydsl_moe1_abf16_wfp4_bf16_t32x64x256_w3_xcd4_kw2   (gate/up GEMM + SiTUv2 epilogue)
    profiled as `moe_gemm1_0` -- 13.53% of e2e-weighted GPU time, the single largest kernel in the
    Kimi-K3 0828 profile (99176 calls / 10624.8 ms; prefill 956.7 us/call, decode 62.3 us/call).
    live seam: AiterRunnerCore.run -> aiter.fused_moe:fused_moe -> fused_moe_2stages
               -> _flydsl_stage1_wrapper (fused_moe.py:1169) -> aiter.ops.flydsl.flydsl_moe_stage1

    The gate/up GEMM, the SiTUv2 activation and the gate*up multiply all live inside this ONE call,
    so the call -- not a single kernel -- is the timed unit. In the 0828 configuration out_dtype is
    'bf16', i.e. stage-1 does NOT fuse the output requant: the call returns one bf16
    [token_num, topk, inter_dim] tensor and the mxfp4 quantization of a2 happens in a separate
    fused_dynamic_mxfp4_quant_moe_sort call outside this seam.

BASELINE  = the FROZEN production package copy in baseline_src/flydsl/ (never kernel_src/).
CANDIDATE = whatever is currently in kernel_src/flydsl/.
speedup   = baseline_ms / candidate_ms, in ANY language/backend (flydsl, aiter, triton, ...).

ROUTING IS REAL: sorted_token_ids / sorted_expert_ids / num_valid_ids in reference_io.pt come from
the SERVED topk distribution of the live TP=8 run (captured at the stage-2 seam of the 0817 session,
inverted back to dense topk_ids/weights and re-sorted by the production aiter moe_sorting at this
stage's own block size) -- it is never synthesized, because the routing skew IS this op's cost
signal. See README.md / meta.routing_provenance for the exact chain and its limits. The
value-INDEPENDENT heavy operands (bf16 hidden states, packed mxfp4 w1 + e8m0 scales) are
re-synthesized deterministically at the live dims/dtypes, and the golden output is the frozen
baseline's own output on them.

DO NOT EDIT THIS FILE, harness_lib.py, reference_io.pt, meta.json or baseline_src/ during optimization.
"""
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# Load the vendored shared harness BEFORE dropping HERE from sys.path / importing torch
# (this file is named unittest.py and would otherwise shadow the stdlib module).
_spec = importlib.util.spec_from_file_location("harness_lib", os.path.join(HERE, "harness_lib.py"))
h = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(h)

sys.path = [p for p in sys.path if os.path.abspath(p or ".") != HERE]

import torch  # noqa: E402

with open(os.path.join(HERE, "meta.json")) as _fh:
    META = json.load(_fh)

REGIME = META["regime"]
GEO = META["geometry"]
TOL = float(META.get("tol", 2e-2))
DEV = "cuda" if torch.cuda.is_available() else "cpu"

# THE KERNEL IS NOT RUN-TO-RUN REPRODUCIBLE. Measured on gfx950 with the live launch variant, and
# reproduced identically through the INSTALLED aiter and through aiter's OWN a16w4 data recipe
# (shuffle_weight_a16w4 / shuffle_scale_a16w4): once the sorted routing spans more than ~50 expert
# blocks, a single launch disagrees with the next on ~0.5-1% of elements (relL2 ~2e-2). Ruled out as
# causes: operand OOB (guard-padded a / w1 / w1_scale), output OOB (a guard row after `out` stays
# exactly zero, so stores ARE masked), the padding marker ((topk<<24)|M, no aliasing, no duplicate
# (token,slot) pairs), every launch knob (k_wave / k_batch / xcd_swizzle / waves_per_eu / b_nt /
# use_async_copy), the call convention (identical to _flydsl_stage1_wrapper), and the machine
# (ut_stage2's UT passes on this node). aiter's own op_test for this path gates it statistically
# (cosine similarity, atol=1.0, pass_pct=95) rather than elementwise, for the same reason.
#
# The disagreement is a MINORITY-VOTE artifact: every element has a stable majority value with
# occasional outliers, so an elementwise median over MEDIAN_LAUNCHES independent launches recovers
# the deterministic result BITWISE (measured: 0/4 unstable trials at K=21 for all three buckets,
# vs 1/4 at K=9 for decode_M64). Correctness therefore compares medians -- which keeps the ordinary
# elementwise tolerance gate meaningful (a real math error still fails at tol=0.02 by 25-450x:
# act=silu -> err 8.9, situ_beta=0.5 -> err 0.50) instead of forcing a tolerance so loose it gates
# nothing. TIMING still measures a SINGLE launch, because that is what the server pays.
MEDIAN_LAUNCHES = int(META.get("median_launches", 21))

E = int(GEO["num_experts"])             # 896 (per-rank expert count)
TOPK = int(GEO["topk"])                 # 16
MODEL_DIM = int(GEO["model_dim"])       # 3584 (hidden size = GEMM K)
INTER_DIM = int(GEO["inter_dim"])       # 384  (= moe_intermediate / TP8; GEMM N is 2*INTER_DIM)


# --------------------------------------------------------------------------- kernel binding

def _load_frozen_capture(torch, path, **kwargs):
    import importlib.util
    from pathlib import Path
    helper = Path(__file__).resolve().with_name("task_contract.py")
    spec = importlib.util.spec_from_file_location("_frozen_capture_loader", helper)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.verified_torch_load(torch, path, **kwargs)


def _load_pkg(root, name, *, frozen=False):
    """Load the exact MoE dependency closure without package-wide reexports."""
    spec = importlib.util.spec_from_file_location(
        "_task_flydsl_package", os.path.join(HERE, "flydsl_package.py"))
    helper = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(helper)
    manifest = os.path.join(HERE, "dependency_manifest.json") if frozen else None
    return helper.load_moe_package(root, name, frozen_manifest=manifest)


_BASELINE_PKG = _load_pkg(os.path.join(HERE, "baseline_src", "flydsl"), "geak_frozen_flydsl", frozen=True)
_CANDIDATE_PKG = _load_pkg(os.path.join(HERE, "kernel_src", "flydsl"), "geak_candidate_flydsl")
ENTRY = META["entry_attr"]                        # "flydsl_moe_stage1"
BASELINE_FN = getattr(_BASELINE_PKG, ENTRY)
CANDIDATE_FN = getattr(_CANDIDATE_PKG, ENTRY)


# --------------------------------------------------------------------------- oracle (REAL routing)
_ORACLE = _load_frozen_capture(torch, os.path.join(HERE, "reference_io.pt"), map_location="cpu", weights_only=False)
ROUTING = {c["spec"]["sig"]: c["routing"] for c in _ORACLE["cases"]}


def _as(dt_name, u8):
    """Reinterpret a byte tensor as the live storage dtype (packed fp4x2 / e8m0)."""
    dt = getattr(torch, dt_name.split(".")[-1], None)
    if dt is None:
        raise TypeError(f"runtime is missing captured storage dtype {dt_name}")
    return u8.view(dt)


def _rand_bytes(shape, lo, hi, gen):
    return torch.randint(lo, hi, tuple(shape), dtype=torch.uint8, device=DEV, generator=gen)


def build_inputs(spec, gen=None):
    """Rebuild ONE case's operands in the LIVE dtypes/layout/launch-variant.

    REAL (served routing, never synthesized): sorted_token_ids, sorted_expert_ids, num_valid_ids
    -- the expert-imbalance signal that sets this grouped GEMM's cost.
    SYNTHESIZED deterministically (value-independent for both cost and the correctness contract):
      a        : (token_num, model_dim)          bfloat16          UNQUANTIZED hidden states
      w1       : (E, 2*inter_dim, model_dim//2)  float4_e2m1fn_x2  packed mxfp4 gate+up weights
      w1_scale : (E*2*inter_dim, model_dim//32)  float8_e8m0fnu    mx group scales

    `a` is drawn from a unit normal rather than from a byte pattern: unlike stage-2, this seam
    consumes the RAW post-RMSNorm hidden states in bf16 (untuned_fmoe_live.csv q_dtype_a=bfloat16,
    so a1_scale is None and the kernel takes the a16w4 path), and RMSNorm output is unit-scale by
    construction.

    The e8m0 group scales are drawn around 2^-10 (byte 117), NOT around 2^0 like stage-2's. That is
    not a free knob -- it is what puts the epilogue in the SERVED regime. A real mxfp4 w1 entry has
    std ~1/sqrt(model_dim); with unit-scale `a` and K=3584 that lands the gate/up GEMM at O(1), which
    is where SiTUv2 actually operates. Scales around 2^0 instead make every accumulator ~90x too
    large, the SiTUv2 output saturates at its +-1 clamp for ~50% of elements, and the kernel's own
    run-to-run spread then shows up as SIGN FLIPS of magnitude 2.0 rather than as rounding -- a
    degenerate oracle that no tolerance can gate. See meta.scale_calibration for the measured sweep.
    """
    lo = int(spec.get("scale_byte_lo", 117))
    hi = int(spec.get("scale_byte_hi", lo + 4))
    sig = spec["sig"]
    if gen is None:
        gen = torch.Generator(device=DEV).manual_seed(int(spec["seed"]))
    tok = int(spec["token_num"])
    routing = {k: v.to(DEV) for k, v in ROUTING[sig].items()}
    if not spec.get("pass_sorted_weights", False):
        routing.pop("sorted_weights", None)      # doweight_stage1=0: topk weights apply in stage-2

    a = torch.randn(tuple(spec["a_shape"]), dtype=torch.bfloat16, device=DEV, generator=gen)
    w1 = _as(spec["w1_dtype_t"], _rand_bytes(spec["w1_shape"], 0, 256, gen))
    w1_scale = _as(spec["scale_dtype_t"], _rand_bytes(spec["w1_scale_shape"], lo, hi, gen))
    a1_scale = None
    if spec.get("pass_a1_scale") and spec.get("a1_scale_shape"):
        a1_scale = _as(spec["scale_dtype_t"], _rand_bytes(spec["a1_scale_shape"], 126, 130, gen))
    return {"a": a, "w1": w1, "w1_scale": w1_scale, "a1_scale": a1_scale,
            "routing": routing, "token_num": tok, "sig": sig,
            "kwargs": dict(spec["kwargs"]), "alloc_out": bool(spec.get("caller_allocates_out", True))}


def fingerprint(args):
    return [int(args["a"].reshape(-1)[:64].view(torch.uint8).sum()),
            int(args["w1"].reshape(-1)[:4096].view(torch.uint8).sum()),
            int(args["routing"]["sorted_token_ids"][:4096].sum()),
            int(args["routing"]["num_valid_ids"][0])]


def _out_of(r):
    """out_dtype='bf16' -> a single tensor. Defensive: a fuse_quant variant (out_dtype fp8/fp4)
    returns (out, out_scale_sorted); only `out` is the comparable payload -- the scale tensor is a
    padded workspace whose tail rows past num_valid_ids are don't-care."""
    return r[0] if isinstance(r, (tuple, list)) else r


def _invoke(fn, args, out=None, zero=False):
    """Call the seam EXACTLY as the live aiter dispatch does.

    fused_moe_2stages allocates a2 = empty((token_num, topk, inter_dim), bf16) and hands it in as
    `out` (it passes None only when metadata.fuse_quant is set, which this variant does not), and
    passes sorted_weights=None because doweight_stage1=0. `zero` defaults to False to match: the
    live caller uses torch.empty, so a memset must not be folded into either leg's timing. It is
    only forced on for the graph-replay bundle, where a stale tail would mask a candidate that
    writes fewer rows than the baseline."""
    r = args["routing"]
    kw = args["kwargs"]
    if out is None and args.get("alloc_out", True):
        out = torch.empty((int(args["token_num"]), TOPK, INTER_DIM),
                          dtype=torch.bfloat16, device=DEV)
    elif out is not None and zero:
        out.zero_()
    return _out_of(fn(args["a"], args["w1"], r["sorted_token_ids"], r["sorted_expert_ids"],
                      r["num_valid_ids"], out, TOPK,
                      w1_scale=args["w1_scale"], a1_scale=args["a1_scale"],
                      sorted_weights=r.get("sorted_weights"),
                      bias=None, topk_ids=None, **kw))


def _invoke_median(fn, args, k=None, stack=None):
    """The CORRECTNESS launcher: elementwise median over k independent launches.

    See the MEDIAN_LAUNCHES note at the top -- a single launch of this kernel is not reproducible,
    the median is. Each launch writes straight into its slice of `stack`, so the extra cost is k
    launches and one k-deep buffer, with no per-launch allocation."""
    k = int(k or MEDIAN_LAUNCHES)
    tok = int(args["token_num"])
    if stack is None:
        stack = torch.empty((k, tok, TOPK, INTER_DIM), dtype=torch.bfloat16, device=DEV)
    for i in range(k):
        _invoke(fn, args, stack[i])
    return stack.median(0).values


def make_call(fn):
    """launcher contract: call(args) -> FRESH out (never a persistent/static buffer)."""
    def call(args):
        return _invoke_median(fn, args)
    return call


baseline_call = make_call(BASELINE_FN)
current_call = make_call(CANDIDATE_FN)


# --------------------------------------------------------------------------- graph-replay bundle
def build_replay(cases_specs):
    """Deployment-context replay: capture ONE graph on the largest decode batch, then replay the
    SMALLER boundary batch through the SAME static buffers -- exactly how the server runs a padded
    decode step under --cuda-graph-max-bs 64 (num_valid_ids shrinks, padded rows are don't-care).
    A candidate that sizes a workspace to the capture shape, that derives its grid from the buffer
    extent instead of num_valid_ids, or that walks past num_valid_ids, faults only here.

    The per-case reference is produced by the FROZEN baseline in the SAME static configuration
    (same padded token_num and same launch variant as the captured graph), never with the case's own
    eager variant -- otherwise a padded replay would be compared against an unpadded launch.
    """
    specs = sorted(cases_specs, key=lambda s: int(s["token_num"]), reverse=True)
    big = build_inputs(specs[0])
    tok_max = int(specs[0]["token_num"])
    r_big = big["routing"]

    st_a = torch.zeros_like(big["a"])
    st_sti = torch.zeros_like(r_big["sorted_token_ids"])
    st_sei = torch.zeros_like(r_big["sorted_expert_ids"])
    st_nvi = torch.zeros_like(r_big["num_valid_ids"])
    st_sw = (torch.zeros_like(r_big["sorted_weights"])
             if r_big.get("sorted_weights") is not None else None)
    st_out = torch.zeros((tok_max, TOPK, INTER_DIM), dtype=torch.bfloat16, device=DEV)
    # static k-deep scratch so the median is computed INSIDE the captured graph (no allocation
    # per replay); replay cases are decode-sized, so this is a few MB.
    st_stack = torch.zeros((MEDIAN_LAUNCHES, tok_max, TOPK, INTER_DIM),
                           dtype=torch.bfloat16, device=DEV)
    st_routing = {"sorted_token_ids": st_sti, "sorted_expert_ids": st_sei, "num_valid_ids": st_nvi}
    if st_sw is not None:
        st_routing["sorted_weights"] = st_sw
    st_args = {"a": st_a, "w1": big["w1"], "w1_scale": big["w1_scale"], "a1_scale": big["a1_scale"],
               "routing": st_routing, "token_num": tok_max,
               "kwargs": dict(big["kwargs"]), "alloc_out": False}
    cur = {"tok": tok_max}

    def fill(case):
        a = case["args"]
        t = int(a["token_num"])
        cur["tok"] = t
        st_a.zero_()
        st_a[:t].copy_(a["a"])
        r = a["routing"]
        # padded slots carry the sorter's own invalid marker (slot index == topk), like the server
        st_sti.fill_(TOPK << 24)
        st_sei.zero_()
        st_sti[: r["sorted_token_ids"].numel()].copy_(r["sorted_token_ids"])
        st_sei[: r["sorted_expert_ids"].numel()].copy_(r["sorted_expert_ids"])
        st_nvi.copy_(r["num_valid_ids"])
        if st_sw is not None and r.get("sorted_weights") is not None:
            st_sw.zero_()
            st_sw[: r["sorted_weights"].numel()].copy_(r["sorted_weights"])

    def _static_median(fn):
        st_stack.zero_()
        for i in range(MEDIAN_LAUNCHES):
            _invoke(fn, st_args, st_stack[i])
        st_out.copy_(st_stack.median(0).values)

    def run():
        _static_median(CANDIDATE_FN)

    def read_out():
        return st_out[: cur["tok"]]

    cases = []
    for sp in specs:
        a = build_inputs(sp)
        a["w1"], a["w1_scale"], a["a1_scale"] = big["w1"], big["w1_scale"], big["a1_scale"]
        if (int(a["routing"]["sorted_token_ids"].numel()) > st_sti.numel()
                or int(a["routing"]["sorted_expert_ids"].numel()) > st_sei.numel()):
            continue                              # cannot be padded into this capture's buffers
        case = {"args": a, "sig": sp["sig"], "_tok": int(sp["token_num"])}
        fill(case)                                # reference in the STATIC (padded) configuration
        _static_median(BASELINE_FN)               # same median contract as run()
        case["ref"] = st_out[: int(sp["token_num"])].clone()
        cases.append(case)

    return {"fill": fill, "run": run, "read_out": read_out, "cases": cases, "capture_idx": 0}


# --------------------------------------------------------------------------- oracle / timing sets
def load_oracle():
    eager_cases, bad_fp = [], []
    for rec in _ORACLE["cases"]:
        args = build_inputs(rec["spec"])
        fp = fingerprint(args)
        if fp != rec["fingerprint"]:
            bad_fp.append((rec["spec"]["sig"], fp, rec["fingerprint"]))
        eager_cases.append({"args": args, "ref": rec["ref"].to(DEV), "sig": rec["spec"]["sig"]})
    return eager_cases, bad_fp


def timing_cases():
    """One case per meta.workload.cases[] entry (own dims + regime), else every frozen case spec."""
    wl = (META.get("workload") or {}).get("cases") or []
    by_sig = {s["sig"]: s for s in META["case_specs"]}
    out = []
    for c in wl:
        spec = c.get("case_spec") or by_sig.get(c.get("name"))
        if spec:
            out.append({"spec": spec, "regime": c.get("regime") or spec.get("regime", "prefill"),
                        "m": c.get("m") or int(spec["token_num"])})
    if not out:
        for spec in META["case_specs"]:
            out.append({"spec": spec, "regime": spec.get("regime", "prefill"),
                        "m": int(spec["token_num"])})
    return out


def time_bucket(entry, warmup, repeats):
    graph = h.deployment_graph_mode(REGIME)
    base = h.compiled_op(BASELINE_FN, REGIME)
    cand = h.compiled_op(CANDIDATE_FN, REGIME)
    args = build_inputs(entry["spec"])
    # Persistent `out`, zero=False: fused_moe_2stages allocates a2 with torch.empty OUTSIDE this
    # seam, so no memset belongs in either leg's timing.
    out = torch.empty((int(args["token_num"]), TOPK, INTER_DIM), dtype=torch.bfloat16, device=DEV)
    b = h.time_op(lambda: _invoke(base, args, out), warmup, repeats, 1, graph, detail=True)
    c = h.time_op(lambda: _invoke(cand, args, out), warmup, repeats, 1, graph, detail=True)
    # Decode buckets pay the launch/graph fixed cost every step, x OSL-amplified: score the
    # launch-INCLUSIVE (wall) sample there; prefill chunks are device-bound.
    pick = ((lambda d: (d or {}).get("wall_ms")) if entry["regime"] == "decode"
            else (lambda d: (d or {}).get("ms")))
    row = {"sig": entry["spec"]["sig"], "regime": entry["regime"], "m": entry["m"],
           "baseline_ms": pick(b), "optimized_ms": pick(c),
           "baseline_device_ms": (b or {}).get("ms"), "optimized_device_ms": (c or {}).get("ms"),
           "timer": (b or {}).get("timer")}
    del args, out
    torch.cuda.empty_cache()
    return row


# --------------------------------------------------------------------------- main
def main():
    argv = sys.argv[1:]
    warmup, repeats = 5, 20
    if "--time-bucket" in argv:                       # fresh-subprocess per-bucket re-measurement
        sig = argv[argv.index("--time-bucket") + 1]
        for e in timing_cases():
            if e["spec"]["sig"] == sig:
                print("GEAK_BUCKET " + json.dumps(time_bucket(e, warmup, repeats)))
                return 0
        print(f"unknown bucket {sig}", file=sys.stderr)
        return 2

    if not torch.cuda.is_available():
        print("ENV: no CUDA/HIP device", file=sys.stderr)
        return 2

    eager_cases, bad_fp = load_oracle()
    if bad_fp:
        print("ENV: deterministic input rebuild MISMATCHED the frozen oracle fingerprint "
              f"(torch/GPU RNG drift): {bad_fp}", file=sys.stderr)
        return 2

    replay = build_replay(META["replay_specs"])
    try:
        ok, report = h.run_correctness(
            REGIME, eager_cases=eager_cases,
            baseline_call=baseline_call, current_call=current_call,
            random_shapes=[{"sig": s["sig"],
                            "make_inputs": (lambda sp: (lambda rng: build_inputs(sp, rng)))(s)}
                           for s in META["case_specs"]],
            tol=TOL, draws=int(META.get("random_draws", 3)), replay=replay)
    except h.HarnessIncompleteError:
        return 3                                       # 3 = regenerate UT (sentinel already printed)

    for leg, rows in report.items():
        for r in rows:
            print(f"[{leg}] {r.get('case')}: correct={r.get('correct')} "
                  f"max_rel_err={r.get('max_rel_err')} {r.get('note','')}")

    seq_ok, seq_rows = h.check_correct_sequence(
        current_call, [eager_cases[i] for i in META.get("call_sequence_idx", [0, 1, 0])], TOL)
    for r in seq_rows:
        print(f"[sequence] {r.get('case')}: correct={r.get('correct')} max_rel_err={r.get('max_rel_err')}")
    ok = ok and seq_ok

    del replay, eager_cases
    torch.cuda.empty_cache()

    per_case = []
    for e in timing_cases():
        row = time_bucket(e, warmup, repeats)
        per_case.append(row)
        print(f"[timing] {row['sig']} m={row['m']} regime={row['regime']} "
              f"baseline_ms={row['baseline_ms']} optimized_ms={row['optimized_ms']} "
              f"(device {row['baseline_device_ms']} / {row['optimized_device_ms']}, timer={row['timer']})")

    res = h.serving_weighted_speedup(per_case, META)
    print("GEAK_PER_CASE " + json.dumps(res["per_case"]))
    print(f"GEAK_GEOMEAN_SPEEDUP {res['geomean']}")
    print(f"GEAK_WEIGHTED_SPEEDUP {res['weighted']}")
    if res["weighted"] is None:
        print(f"GEAK_WEIGHT_UNTRUSTED {res['reason']}")
    print("GEAK_CORRECT " + ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
