# Copyright(C) [2026] Advanced Micro Devices, Inc. All rights reserved.
"""Unified Forge registration; both engine workflows consume the public v2 task contract.

The launcher delegates to adapter.py. Legacy private utility imports/builders
remain temporarily available to callers, but are not used by v2 execution.
"""

from __future__ import annotations

import json
import logging
import shlex
import shutil
from pathlib import Path
from typing import Any

import yaml

from agents import register_agent
from agents.forge.common import (
    FORGE_RESULT_SENTINEL as _FORGE_RESULT_SENTINEL,
    FORGE_SHUTDOWN_MARGIN_SECONDS as _FORGE_SHUTDOWN_MARGIN_SECONDS,
    KB_STATUS_FILE as _KB_STATUS_FILE,
    _declared_editable_sources,
    _forge_max_hours,
    _git,
    _infer_backend,
    _init_git_workspace,
    _logical_operator,
    _normalize_logical_operator,
    _read_forge_result,
    _resolve_all_source_files,
    _resolve_fellow,
    _resolve_framework,
    _resolve_gpu_arch,
    _resolve_gpu_type,
    _resolve_kernel_backend,
    _resolve_kernel_file,
    _resolve_kernel_kind,
    _strip_nested_git,
    _task_kernel_identity,
    _terminate_process_group,
    forge_environment,
    resolve_forge_binary,
    run_forge_subprocess,
)


def _render_driver_shim(drivers_dir: str, workspace: str, task_config: str, arena_root: str) -> str:
    """Generate a forge_driver.py that bakes the task paths in (no env needed).

    The shim adds the shared adapter's dir to sys.path and delegates to
    ``arena_task_adapter.run``, passing workspace / task config / arena root as
    explicit arguments. KernelForge invokes this file as ``python forge_driver.py
    <args>`` (see kernel_agents.mcp_server.tools.{test,bench}), so a ``__main__``
    entry is all that is required.
    """
    return f"""\
#!/usr/bin/env python3
# Auto-generated by the AgentKernelArena forge launcher. Task paths are baked in
# below so the driver needs NO environment variables. It delegates to the shared
# arena_task_adapter, which reuses Arena's own correctness/performance eval.
import sys

sys.path.insert(0, {drivers_dir!r})
import arena_task_adapter as adapter

WORKSPACE = {workspace!r}
TASK_CONFIG = {task_config!r}
ARENA_ROOT = {arena_root!r}

if __name__ == "__main__":
    raise SystemExit(adapter.run(WORKSPACE, TASK_CONFIG, ARENA_ROOT, sys.argv[1:]))
"""


def _build_forge_command(
    *,
    forge_bin: str,
    kernel_file: Path,
    driver_dest: Path,
    workspace: str,
    experiments_dir: Path,
    result_json: Path,
    agent_config: dict[str, Any],
    gpu_arch: str,
    gpu_type: str,
    kernel_backend: str,
    task_type: str,
    source_files: list[Path],
    target_functions: list[str],
    logical_operator: str,
    framework: str,
) -> list[str]:
    """Build argv without shell parsing so task metadata is forwarded exactly.

    Targets KernelForge as it now ships inside Hyperloom (``src/kernelforge``).
    Two options the pre-merge standalone repo took are gone there, and click
    rejects an unknown option outright, so this argv does not run against that
    older tree at all:

      --max-iters  removed upstream; the loop is budgeted purely by time
                   (``--max-hours`` plus its own deadline), so there is nothing
                   to translate an iteration cap into.
      --fellow     the fellow concept was removed; ``--kernel-backend`` is its
                   replacement. Translated rather than dropped, because an unset
                   backend falls back to flydsl -- which would quietly optimise
                   a Triton kernel down a different path instead of failing.
                   ``kernel_backend`` arrives already validated against the
                   installed registry by ``_resolve_kernel_backend``; do not
                   derive it from the fellow name here.
    """
    cmd = [
        forge_bin,
        "forge-loop",
        "--kernel",
        str(kernel_file),
        "--driver",
        str(driver_dest),
        "--workspace",
        str(workspace),
        "--experiments-dir",
        str(experiments_dir),
        "--result-json",
        str(result_json),
        "--snr-threshold",
        str(agent_config.get("snr_threshold", 30.0)),
        "--max-hours",
        str(_forge_max_hours(agent_config)),
        "--gpu-target",
        gpu_arch,
        "--gpu-type",
        gpu_type,
        "--kernel-backend",
        kernel_backend,
        "--git-branch",
        "forge-optimize",
        "--model",
        str(agent_config.get("model", "claude-opus-4-8")),
        "--permission-mode",
        str(agent_config.get("permission_mode", "acceptEdits")),
        "--task-type",
        task_type,
    ]
    if source_files:
        cmd.extend(["--source-files", ",".join(str(path) for path in source_files)])
    if target_functions:
        cmd.extend(["--target-functions", ",".join(str(name) for name in target_functions)])
    if logical_operator:
        cmd.extend(["--operator-name", logical_operator])
    if framework:
        cmd.extend(["--framework", framework])
    return cmd


def _publication_status(result: dict[str, Any] | None) -> dict[str, Any]:
    """Summarize optional remote publication diagnostics."""
    def _authoritative(publication: Any) -> bool:
        if not isinstance(publication, dict) or "published_commit" not in publication:
            return False
        return (
            "pending_commit" in publication
            or publication.get("status") == "warm_start_existing"
        )

    status: dict[str, Any] = {
        "published": False,
        "latest_best_published": False,
        "authoritative": False,
        "state": "result_missing" if result is None else "not_published",
        "reason": "",
        "best_commit": "",
        "published_commit": "",
        "pending_commit": "",
    }
    if result is None:
        status["reason"] = "forge_result_missing"
        return status

    best_commit = str(result.get("best_commit") or "")
    status["best_commit"] = best_commit
    top_level = result.get("remote_publication")
    publication = top_level if isinstance(top_level, dict) else None
    source = "remote_publication"
    kb_experience = result.get("kb_experience")
    top_level_authoritative = _authoritative(publication)
    if not top_level_authoritative and isinstance(kb_experience, dict):
        nested = kb_experience.get("publication")
        nested_authoritative = _authoritative(nested)
        if nested_authoritative or publication is None:
            publication = nested
            source = "kb_experience.publication"
    if publication is None:
        status["state"] = "schema_unsupported"
        status["reason"] = (
            "forge result has neither remote_publication nor "
            "kb_experience.publication"
        )
        return status

    status["source"] = source
    status["authoritative"] = _authoritative(publication)
    published_commit = str(publication.get("published_commit") or "")
    pending_commit = str(publication.get("pending_commit") or "")
    status["published_commit"] = published_commit
    status["pending_commit"] = pending_commit
    status["publication_state"] = str(publication.get("status") or "")
    latest_best_published = bool(
        status["authoritative"]
        and best_commit
        and published_commit == best_commit
        and not pending_commit
    )
    status["published"] = latest_best_published
    status["latest_best_published"] = latest_best_published
    status["state"] = (
        "published"
        if latest_best_published
        else str(publication.get("status") or "not_published")
    )
    if not best_commit:
        status["reason"] = "best_commit_missing"
    elif not status["authoritative"]:
        status["reason"] = "publication_schema_incomplete"
    elif pending_commit:
        status["reason"] = f"publication_pending:{pending_commit}"
    elif published_commit != best_commit:
        status["reason"] = (
            f"published_commit_mismatch:{published_commit or '<none>'}!={best_commit}"
        )

    if isinstance(kb_experience, dict):
        final_write = kb_experience.get("write")
        if isinstance(final_write, dict):
            status["final_write"] = {
                key: final_write[key]
                for key in ("written", "reason")
                if key in final_write
            }
    return status


def _write_forge_status(
    experiments_dir: Path,
    *,
    returncode: int | None,
    timed_out: bool,
    result: dict[str, Any] | None,
    kb_status: dict[str, Any],
) -> dict[str, Any]:
    summary = {
        "exit_code": returncode,
        "timed_out": timed_out,
        "kb": kb_status,
        "experiment_id": (result or {}).get("experiment_id", ""),
        "improved": bool((result or {}).get("improved", False)),
        "best_iteration": (result or {}).get("best_iteration", 0),
    }
    experiments_dir.mkdir(parents=True, exist_ok=True)
    (experiments_dir / _KB_STATUS_FILE).write_text(
        json.dumps(summary, indent=2, sort_keys=True)
    )
    return summary


@register_agent("forge")
def launch_agent(eval_config: dict[str, Any], task_config_dir: str, workspace: str) -> str:
    """Run the unified v2 adapter. Private legacy helpers above are not routing."""
    from agents.forge.adapter import launch
    return launch(eval_config, task_config_dir, workspace)
