agent:
  template: mini_swe_triton

tasks:
  - triton2triton/geak_eval/L1/fused_append_shared_experts
  - triton2triton/geak_eval/L1/mla_decode
  - triton2triton/geak_eval/L3/gemm
  - triton2triton/geak_eval/L3/gemm_a16w16_atomic
  - triton2triton/geak_eval/L3/fused_qk_rope_cache_mla
  - triton2triton/geak_eval/L3/fused_mxfp4_quant_moe_sort
  - triton2triton/geak_eval/L3/fused_moe_mxfp4
  - triton2triton/geak_eval/L2/rope

target_gpu_model: MI300
log_directory: logs
workspace_directory_prefix: workspace_mini_swe
