agent:
  template: mini_swe_triton

tasks:
  - triton2triton/geak_eval/L1/llama_ff_triton
  - triton2triton/geak_eval/L1/moe_routing_sigmoid_top1
  - triton2triton/geak_eval/L2/topk
  - triton2triton/geak_eval/L2/fast_rms_layernorm
  - triton2triton/geak_eval/L2/lean_atten_paged
  - triton2triton/geak_eval/L3/fused_qkv_rope
  - triton2triton/geak_eval/L3/fused_rms_fp8
  - triton2triton/geak_eval/L3/gemm_a16wfp4

target_gpu_model: MI300
log_directory: logs
workspace_directory_prefix: workspace_mini_swe
