version: 0

# Agent timeout settings
timeout_seconds: 36000
python_path: python3

run:
  # cmd can be mini or geak
  cmd: mini
  # Additional options for the agent
  configs: '-c geak.yaml --yolo --num-parallel=2 --gpu-ids=0,1'