version: 0

# Agent timeout settings
timeout_seconds: 36000
python_path: python3

run:
  # cmd: the CLI entrypoint
  cmd: geak
  # Additional options for the agent
  configs: '-c geak.yaml --yolo --num-parallel=2 --gpu-ids=4,5'