"""Real filesystem regressions for all four replacement-port package hashes."""
import ast
import hashlib
from pathlib import Path

import pytest

REPO=Path(__file__).resolve().parents[1]
PORTS=('glm-5.3-flash__fused_moe_kernel','glm-5.3-flash__gemm_a16w16_bf16_cijk',
       'glm-5.3-flash__ck_gemm_a8w8_blockscale_bpreshuffle','kimi-k3__dense_bf16_gemm_cijk')


@pytest.fixture(params=PORTS)
def package(request,tmp_path):
    path=REPO/'tasks/headkernel'/request.param/'scripts/task_runner.py'
    tree=ast.parse(path.read_text())
    function=next(node for node in tree.body if isinstance(node,ast.FunctionDef) and node.name=='package_hash')
    def file_sha(path):
        with Path(path).open('rb') as stream:return hashlib.file_digest(stream,'sha256').hexdigest()
    namespace={'ROOT':tmp_path,'hashlib':hashlib,'file_sha':file_sha}
    # Execute the real function, without importing unrelated GPU dependencies.
    exec(compile(ast.Module(body=[function],type_ignores=[]),str(path),'exec'),namespace)
    for name,data in [('source/kernels.py',b'GPU body'),('ut/reference/kernels.py',b'frozen GPU body'),
                      ('ut/oracle.py',b'protected oracle'),('fixtures/blob.bin',b'captured storage'),
                      ('cases.json',b'cases and scalar arguments')]:
        file=tmp_path/name;file.parent.mkdir(parents=True,exist_ok=True);file.write_bytes(data)
    return tmp_path,namespace['package_hash']


def test_streamed_validator_logs_and_native_extension_outputs_do_not_change_hash(package):
    root,digest=package
    audit=root/'.validator_audit';audit.mkdir()
    stderr=audit/'compile_1.stderr.log';stderr.write_text('')
    before=digest()
    with stderr.open('a') as stream:
        stream.write('[aiter] import [module_aiter_core]\n');stream.flush()
        assert digest()==before
        stream.write('[aiter] native kernel loaded\n');stream.flush()
        (audit/'attempt.json').write_text('{"running":true}')
        cache=root/'.validator_torch_extensions';cache.mkdir()
        (cache/'extension.so').write_bytes(b'compiled runtime extension')
        build=root/'build';build.mkdir();(build/'compile_report.json').write_text('{"compiled":true}')
        assert digest()==before


@pytest.mark.parametrize('name',[
    'source/kernels.py','ut/reference/kernels.py','ut/oracle.py','fixtures/blob.bin','cases.json',
    'ut/build/native_header.h','fixtures/nested/build/storage.bin',
    'ut/.validator_audit/critical.py','fixtures/.validator_torch_extensions/critical.bin',
    '.validator_audit_backup/input.json','ut/protected_bytecode.pyc',
])
def test_immutable_inputs_and_nested_runtime_names_stay_hashed(package,name):
    root,digest=package;before=digest();path=root/name;path.parent.mkdir(parents=True,exist_ok=True)
    path.write_bytes(b'changed protected input')
    assert digest()!=before


@pytest.mark.parametrize('kind',['file','directory','dangling','runtime_root'])
def test_file_directory_and_dangling_symlinks_are_rejected(package,kind):
    root,digest=package
    if kind=='file':(root/'source/alias.py').symlink_to('kernels.py')
    elif kind=='directory':
        (root/'ut').rename(root/'real-ut');(root/'ut').symlink_to('real-ut',target_is_directory=True)
    elif kind=='dangling':(root/'source/missing.py').symlink_to('absent.py')
    else:(root/'.validator_audit').symlink_to('ut',target_is_directory=True)
    with pytest.raises(ValueError,match='symlink'):digest()


def test_python_bytecode_cache_remains_runtime_output(package):
    root,digest=package;before=digest();cache=root/'ut/__pycache__';cache.mkdir()
    (cache/'oracle.cpython-312.pyc').write_bytes(b'generated bytecode')
    assert digest()==before
