// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_rms_norm` namespace so the task
// can call torch.ops.extracted_rms_norm.rms_norm without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void rms_norm(torch::Tensor& out, torch::Tensor& input, torch::Tensor& weight, double epsilon);

TORCH_LIBRARY(extracted_rms_norm, m) {
    m.def("rms_norm(Tensor! result, Tensor input, Tensor weight, float epsilon) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_rms_norm, CUDA, m) {
    m.impl("rms_norm", &rms_norm);
}
