// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_wvsplitk` namespace so the task
// can call torch.ops.extracted_wvsplitk.wvSplitK without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

torch::Tensor wvSplitK(const at::Tensor& in_a, const at::Tensor& in_b, const std::optional<at::Tensor>& in_bias, const int64_t CuCount);

TORCH_LIBRARY(extracted_wvsplitk, m) {
    m.def("wvSplitK(Tensor in_a, Tensor in_b, Tensor? in_bias, int CuCount) -> Tensor");
}

TORCH_LIBRARY_IMPL(extracted_wvsplitk, CUDA, m) {
    m.impl("wvSplitK", &wvSplitK);
}
