version: 0

# Agent timeout settings
timeout_seconds: 36000
python_path: python3

run:
  # cmd can be mini or geak
  cmd: mini
  # Number of GPUs each task needs (used by both mini agent and run_parallel.py)
  num_parallel: 2
  # Additional options for the agent
  configs: '-c geak.yaml --yolo'