#!/usr/bin/env python3
"""IMMUTABLE unittest for the aiter fused MoE STAGE-1 launcher (a8w4: mxfp8 acts x mxfp4 experts).

Judges correctness against the FROZEN live-captured oracle AND measures the workload-weighted
speedup. Both legs are the SAME code under two PYTHONPATHs (baseline_overlay = the live serving
stack; _cand_overlay = that stack + kernel_src/ via meta.candidate_bind) — this file never binds a
"baseline callable" and never imports a backend by name.

Do NOT edit this file, cases.py, harness_lib.py, leg_runner.py, overlay_setup.py or reference_io.pt
during optimization; kernel_src/ is the only writable path in this task dir.

Exit codes: 0 pass | 1 correctness FAIL | 2 environment error | 3 UT harness incomplete (regenerate).
"""
import importlib
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


# harness_lib FIRST, then drop HERE from sys.path (this file is named unittest.py and would shadow
# the stdlib module for torch and friends).
h = _load("harness_lib", os.path.join(HERE, "harness_lib.py"))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != HERE]

with open(os.path.join(HERE, "meta.json")) as _fh:
    META = json.load(_fh)
cases = _load("cases", os.path.join(HERE, "cases.py"))
TOL = float(META.get("tol", 0.15))          # fp8 e4m3 out: one code step is ~12.5% relative


def _resolve(dotted):
    mod_name, _, attr = dotted.partition(":")
    obj = importlib.import_module(mod_name)
    for part in attr.split("."):
        if part:
            obj = getattr(obj, part)
    return obj


# --------------------------------------------------------------------- deployment graph-replay bundle
def _build_replay(torch, recs):
    """Capture-once / replay-many over >=2 BOUNDARY decode shapes sharing ONE set of static buffers.

    The live server replays this op inside a HIP graph (regime.cuda_graph=true), so the static input
    AND output storage is reused across differently-shaped decode batches. Static buffers are sized on
    the LARGEST decode case (M=64); the smaller one (M=32) is padded into them exactly as the server
    pads a decode batch (rows beyond M zeroed; the sorted block map padded with its own out-of-range
    sentinel). Both cases run the SAME live kernel name, so the captured graph is the deployed one.
    """
    gr = META.get("graph_replay") or {}
    by_sig = {r["sig"]: r for r in recs}
    cap, second = by_sig.get(gr.get("capture_sig")), by_sig.get(gr.get("second_sig"))
    if cap is None or second is None:
        return None

    base = cap["args"]
    out_key = META.get("out_key", "out")
    st_args = [t.clone() if torch.is_tensor(t) else t for t in base["args"]]
    st_kwargs = {k: (v.clone() if torch.is_tensor(v) else v) for k, v in base["kwargs"].items()}
    ref0 = cap["ref"]
    # The seam allocates `out` itself when out=None (as the live dispatcher passes it). A graph-safe
    # replay needs ONE stable output storage, so hand it the static buffer explicitly — the seam then
    # writes in place instead of allocating, exactly like a server that pre-allocates its decode
    # buffer. The second return component (out_scale_sorted) is still allocated inside the seam; its
    # size depends only on the STATIC sorted_token_ids length, so it lands in the graph's private
    # pool once at capture and is rewritten in place on every replay.
    st_out = torch.zeros_like(ref0)
    st_kwargs[out_key] = st_out
    fn = _resolve(META["target_callable"])
    state = {"m": int(ref0.shape[0])}

    def _byte(t):
        # mxfp4 / e8m0 tensors have no zero_/copy_ kernels; operate on their raw byte view instead
        # (both sides always carry the SAME dtype here, so a byte copy is exact).
        try:
            torch.empty(1, dtype=t.dtype, device=t.device).zero_()
            return t
        except (NotImplementedError, RuntimeError, TypeError):
            return t.view(torch.uint8)

    def _fill_tensor(dst, src, pad):
        d, s = _byte(dst), _byte(src)
        d.zero_()
        n = min(d.shape[0], s.shape[0])
        d[:n].copy_(s[:n])
        if n < d.shape[0] and pad is not None:
            dst[n:] = pad

    def _pad_for(dst, src):
        # the sorted block map pads with an out-of-range sentinel; reuse the STATIC case's own
        # sentinel (it encodes the static token_num) for the tail beyond this case's length.
        if dst.dim() == 1 and dst.shape[0] > src.shape[0]:
            return dst[-1].clone()
        return None

    def fill(case):
        a = case["args"]
        state["m"] = int(case["ref"].shape[0])
        for i, src in enumerate(a["args"]):
            if not torch.is_tensor(src):
                continue
            _fill_tensor(st_args[i], src, _pad_for(st_args[i], src))
        for k, src in a["kwargs"].items():
            if k == out_key or not torch.is_tensor(src):
                continue
            dst = st_kwargs.get(k)
            if torch.is_tensor(dst):
                _fill_tensor(dst, src, _pad_for(dst, src))
        st_out.zero_()

    def run():
        fn(*st_args, **st_kwargs)

    def read_out():
        return st_out[:state["m"]]

    return {"fill": fill, "run": run, "read_out": read_out, "capture_idx": 0,
            "cases": [{"args": cap["args"], "ref": cap["ref"], "sig": "replay:" + cap["sig"][:40]},
                      {"args": second["args"], "ref": second["ref"],
                       "sig": "replay:" + second["sig"][:40]}]}


def main():
    torch = h._torch()
    if not torch.cuda.is_available():
        print("ENV FAIL: no CUDA device")
        return 2

    recs = cases.oracle_records(h, META)
    eager = cases.eager_cases(h, META)
    rnd = cases.random_shapes(h, META)
    draws = int(META.get("random_draws", 3))

    # baseline outputs for the random-value parity leg are recorded by the BASELINE leg in its OWN
    # process (leg_runner --mode oracle under baseline_overlay/), never by an in-process callable.
    base_out = h.baseline_random_outputs(HERE, META, draws=draws)

    replay = _build_replay(torch, recs)
    try:
        ok, report = h.run_correctness(META["regime"], eager_cases=eager, current_call=cases.call,
                                       random_shapes=rnd, tol=TOL, baseline_outputs=base_out,
                                       draws=draws, replay=replay)
    except h.HarnessIncompleteError:
        return 3                    # sentinel already printed by run_correctness

    for leg, rows in report.items():
        for r in rows or []:
            print(f"[correctness/{leg}] {r.get('case','')}: "
                  f"{'PASS' if r.get('correct') else 'FAIL'} err={r.get('max_rel_err')}"
                  + (f" note={r['note']}" if r.get("note") else ""))

    # ADDITIVE: the seam returns (inter_states_fp8, out_scale_sorted_e8m0). `cases.call` returns the
    # first component (so the harness's shared-buffer/data_ptr check stays meaningful). The SECOND
    # component is gated STRUCTURALLY here (arity / dtype / shape), NOT by value — measured on this
    # box, `out_scale_sorted` is a SCRATCH buffer the launcher allocates with torch.empty and writes
    # only over the tiles it computes: outside those tiles it is uninitialized garbage (e8m0 0xFF =
    # NaN), and even at the real sorted slots two CONSECUTIVE BASELINE calls disagree, while the
    # frozen capture's copy of it does not reproduce at all (decode: recorded median exponent 0 vs
    # live 116). Value-gating it therefore FAILS THE LIVE BASELINE AGAINST ITSELF — a UT defect, not
    # a kernel signal. The scales stay gated INDIRECTLY and exactly: component 0 is the fp8 mantissa
    # of the SAME product (mantissa = value / 2**scale), bit-exact vs the frozen oracle and vs the
    # live baseline on every random draw, so any candidate that changes the block scales moves the
    # mantissas too and is caught above. Residual (scales corrupted while mantissas stay identical)
    # is covered by the e2e output-parity gate.
    full_outs = [cases.call_full(r["args"]) for r in recs]
    for r, out in zip(recs, full_outs):
        ref_parts = r["ref_full"] if isinstance(r["ref_full"], (tuple, list)) else (r["ref_full"],)
        out_parts = out if isinstance(out, (tuple, list)) else (out,)
        c_ok, why = len(out_parts) == len(ref_parts), ""
        if not c_ok:
            why = f"arity {len(out_parts)} != oracle {len(ref_parts)}"
        for i, (o, f) in enumerate(zip(out_parts, ref_parts)):
            if o is None or f is None:
                if (o is None) != (f is None):
                    c_ok, why = False, f"component {i} None-ness differs"
                continue
            if o.dtype != f.dtype or tuple(o.shape) != tuple(f.shape):
                c_ok, why = False, (f"component {i} {o.dtype}{tuple(o.shape)} != "
                                    f"oracle {f.dtype}{tuple(f.shape)}")
        ok = ok and c_ok
        print(f"[correctness/full_output_struct] {r['sig'][:60]}: "
              f"{'PASS' if c_ok else 'FAIL'}{(' ' + why) if why else ''} "
              f"(values of the e8m0 scale component are NOT gated in isolation — scratch buffer, "
              f"see comment; component 0 is value-gated bit-exactly above)")
    del full_outs

    # real recorded interleave (chunked-prefill big-M -> decode M=1) to catch cross-call stale state
    order = [c.get("sig") for c in (META.get("call_sequence") or [])]
    by_sig = {r["sig"]: r for r in recs}
    ordered = [{"args": by_sig[s]["args"], "ref": by_sig[s]["ref"], "sig": s}
               for s in order if s in by_sig]
    if ordered:
        s_ok, s_rows = h.check_correct_sequence(cases.call, ordered, TOL)
        ok = ok and s_ok
        for r in s_rows:
            print(f"[correctness/sequence] {r['case'][:70]}: "
                  f"{'PASS' if r.get('correct') else 'FAIL'} err={r.get('max_rel_err')}")

    print(f"CORRECTNESS: {'PASS' if ok else 'FAIL'}")

    # ---------------------------------------------------------------- timing (both legs, per bucket)
    per_case = h.measure_legs(HERE, META)
    for c in per_case:
        print(f"[timing] m={c.get('m')} regime={c.get('regime')} "
              f"baseline_ms={c.get('baseline_ms')} optimized_ms={c.get('optimized_ms')} "
              f"speedup={c.get('speedup')} reps={c.get('reps')} spread={c.get('speedup_spread')}")
    res = h.serving_weighted_speedup(per_case, META)
    print(json.dumps({"per_case": res["per_case"], "included": res["included"],
                      "dropped_unserved": res["dropped_unserved"],
                      "suspect_identity": res["suspect_identity"], "reason": res["reason"]}))
    print(f"GEAK_GEOMEAN_SPEEDUP: {res['geomean']}")
    print(f"GEAK_WEIGHTED_SPEEDUP: {res['weighted']}")
    return 0 if ok else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except h.HarnessIncompleteError:
        sys.exit(3)
