// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_topk_softmax` namespace so the task
// can call torch.ops.extracted_topk_softmax.topk_softmax without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void topk_softmax( torch::Tensor& topk_weights, torch::Tensor& topk_indices, torch::Tensor& token_expert_indices, torch::Tensor& gating_output, bool renormalize, std::optional<torch::Tensor> bias);

TORCH_LIBRARY(extracted_topk_softmax, m) {
    m.def("topk_softmax(Tensor! topk_weights, Tensor! topk_indices, Tensor! token_expert_indices, Tensor gating_output, bool renormalize, Tensor? bias) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_topk_softmax, CUDA, m) {
    m.impl("topk_softmax", &topk_softmax);
}
