#!/usr/bin/env python3
"""IMMUTABLE unittest for the aiter OPUS MoE STAGE-2 SEGMENT (a8w4: mxfp8 acts x mxfp4 experts).

Scope = the profiled SEGMENT, not one kernel: the seam
`aiter.ops.opus.moe_stage2_a8w4_fused_adapter:opus_a8w4_stage2_wrapper` owns BOTH profiled device
kernels (`opus_moe_stage2_a8w4_decode_kernel_gfx950` down-GEMM and
`opus_moe_stage2_reduce_token_slot_route_output_kernel_gfx950` top-k reduce). Every deeper python
callable owns only one of the two, so timing here is the sum the profile attributes to this head.

Judges correctness against the FROZEN live-captured oracle AND measures the workload-weighted
speedup. Both legs are the SAME code under two PYTHONPATHs (baseline_overlay = the live serving
stack; _cand_overlay = that stack + kernel_src/ via meta.candidate_bind) — this file never binds a
"baseline callable" and never imports a backend by name.

Do NOT edit this file, cases.py, harness_lib.py, leg_runner.py, overlay_setup.py or reference_io.pt
during optimization; kernel_src/ is the only writable path in this task dir.

Exit codes: 0 pass | 1 correctness FAIL | 2 environment error | 3 UT harness incomplete (regenerate).
"""
import importlib
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


# harness_lib FIRST, then drop HERE from sys.path (this file is named unittest.py and would shadow
# the stdlib module for torch and friends).
h = _load("harness_lib", os.path.join(HERE, "harness_lib.py"))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != HERE]

with open(os.path.join(HERE, "meta.json")) as _fh:
    META = json.load(_fh)
cases = _load("cases", os.path.join(HERE, "cases.py"))
# bf16 out (~3 decimal digits); the decode path ATOMICALLY accumulates the topk partials, so the
# summation order is nondeterministic run-to-run even for the untouched baseline.
TOL = float(META.get("tol", 0.02))


def _resolve(dotted):
    mod_name, _, attr = dotted.partition(":")
    obj = importlib.import_module(mod_name)
    for part in attr.split("."):
        if part:
            obj = getattr(obj, part)
    return obj


# --------------------------------------------------------------------- deployment graph-replay bundle
def _build_replay(torch, recs):
    """Capture-once / replay-many over >=2 BOUNDARY decode shapes sharing ONE set of static buffers.

    The live server replays this op inside a HIP graph (regime.cuda_graph=true), so the static input
    AND output storage is reused across differently-shaped decode batches. Static buffers are sized on
    the LARGEST decode case (M=256); the smaller one (M=64) is padded into them exactly as the server
    pads a decode batch (rows beyond M zeroed; the sorted block map padded with its own out-of-range
    sentinel, and `num_valid_ids` copied from the small case so the kernel walks only its own blocks).
    Both cases run the SAME live kernel (kernel_id 2005, `opus_moe2_afp8_wfp4_atomic_...sbm32...`), so
    the captured graph is the deployed one.

    This seam takes `out` POSITIONALLY (meta.inplace_out_arg = 6) and writes it in place, so the static
    output buffer is installed at that position — and re-zeroed on every fill, which the atomic
    accumulate path requires.
    """
    gr = META.get("graph_replay") or {}
    by_sig = {r["sig"]: r for r in recs}
    cap, second = by_sig.get(gr.get("capture_sig")), by_sig.get(gr.get("second_sig"))
    if cap is None or second is None:
        return None

    base = cap["args"]
    out_key = META.get("out_key", "out")
    out_idx = META.get("inplace_out_arg")
    out_idx = int(out_idx) if out_idx is not None else None
    st_args = [t.clone() if torch.is_tensor(t) else t for t in base["args"]]
    st_kwargs = {k: (v.clone() if torch.is_tensor(v) else v) for k, v in base["kwargs"].items()}
    ref0 = cap["ref"]
    st_out = torch.zeros_like(ref0)
    if out_idx is not None and 0 <= out_idx < len(st_args):
        st_args[out_idx] = st_out
    else:
        st_kwargs[out_key] = st_out
    fn = _resolve(META["target_callable"])
    state = {"m": int(ref0.shape[0])}

    def _byte(t):
        # mxfp4 / e8m0 tensors have no zero_/copy_ kernels; operate on their raw byte view instead
        # (both sides always carry the SAME dtype here, so a byte copy is exact).
        try:
            torch.empty(1, dtype=t.dtype, device=t.device).zero_()
            return t
        except (NotImplementedError, RuntimeError, TypeError):
            return t.view(torch.uint8)

    def _fill_tensor(dst, src, pad):
        d, s = _byte(dst), _byte(src)
        d.zero_()
        n = min(d.shape[0], s.shape[0])
        d[:n].copy_(s[:n])
        if n < d.shape[0] and pad is not None:
            dst[n:] = pad

    def _pad_for(dst, src):
        # the sorted block map pads with an out-of-range INTEGER sentinel; reuse the STATIC case's own
        # sentinel (it encodes the static token_num) for the tail beyond this case's length. Float
        # 1-D operands (sorted_weights) are left zeroed instead — a sentinel would be a bogus weight.
        if dst.dim() == 1 and dst.shape[0] > src.shape[0] and not dst.is_floating_point():
            return dst[-1].clone()
        return None

    def fill(case):
        a = case["args"]
        state["m"] = int(case["ref"].shape[0])
        for i, src in enumerate(a["args"]):
            if i == out_idx or not torch.is_tensor(src):
                continue
            _fill_tensor(st_args[i], src, _pad_for(st_args[i], src))
        for k, src in a["kwargs"].items():
            if k == out_key or not torch.is_tensor(src):
                continue
            dst = st_kwargs.get(k)
            if torch.is_tensor(dst):
                _fill_tensor(dst, src, _pad_for(dst, src))
        st_out.zero_()          # MANDATORY: the decode kernel atomically ACCUMULATES into `out`

    def run():
        fn(*st_args, **st_kwargs)

    def read_out():
        return st_out[:state["m"]]

    return {"fill": fill, "run": run, "read_out": read_out, "capture_idx": 0,
            "cases": [{"args": cap["args"], "ref": cap["ref"], "sig": "replay:" + cap["sig"][:40]},
                      {"args": second["args"], "ref": second["ref"],
                       "sig": "replay:" + second["sig"][:40]}]}


def main():
    torch = h._torch()
    if not torch.cuda.is_available():
        print("ENV FAIL: no CUDA device")
        return 2

    recs = cases.oracle_records(h, META)
    eager = cases.eager_cases(h, META)
    rnd = cases.random_shapes(h, META)
    draws = int(META.get("random_draws", 3))

    # baseline outputs for the random-value parity leg are recorded by the BASELINE leg in its OWN
    # process (leg_runner --mode oracle under baseline_overlay/), never by an in-process callable.
    base_out = h.baseline_random_outputs(HERE, META, draws=draws)

    replay = _build_replay(torch, recs)
    try:
        ok, report = h.run_correctness(META["regime"], eager_cases=eager, current_call=cases.call,
                                       random_shapes=rnd, tol=TOL, baseline_outputs=base_out,
                                       draws=draws, replay=replay)
    except h.HarnessIncompleteError:
        return 3                    # sentinel already printed by run_correctness

    for leg, rows in report.items():
        for r in rows or []:
            print(f"[correctness/{leg}] {r.get('case','')}: "
                  f"{'PASS' if r.get('correct') else 'FAIL'} err={r.get('max_rel_err')}"
                  + (f" note={r['note']}" if r.get("note") else ""))

    # ADDITIVE: the seam returns exactly ONE tensor (the in-place `out` it was handed). Gate its
    # arity/dtype/shape structurally so a candidate cannot silently change the return contract (e.g.
    # start returning the per-slot route_out partials, or an fp8 buffer) while still matching values
    # on the sliced comparison above.
    full_outs = [cases.call_full(r["args"]) for r in recs]
    for r, out in zip(recs, full_outs):
        ref_parts = r["ref_full"] if isinstance(r["ref_full"], (tuple, list)) else (r["ref_full"],)
        out_parts = out if isinstance(out, (tuple, list)) else (out,)
        c_ok, why = len(out_parts) == len(ref_parts), ""
        if not c_ok:
            why = f"arity {len(out_parts)} != oracle {len(ref_parts)}"
        for i, (o, f) in enumerate(zip(out_parts, ref_parts)):
            if o is None or f is None:
                if (o is None) != (f is None):
                    c_ok, why = False, f"component {i} None-ness differs"
                continue
            if o.dtype != f.dtype or tuple(o.shape) != tuple(f.shape):
                c_ok, why = False, (f"component {i} {o.dtype}{tuple(o.shape)} != "
                                    f"oracle {f.dtype}{tuple(f.shape)}")
        ok = ok and c_ok
        print(f"[correctness/full_output_struct] {r['sig'][:60]}: "
              f"{'PASS' if c_ok else 'FAIL'}{(' ' + why) if why else ''}")
    del full_outs

    # real recorded interleave (chunked-prefill big-M route+reduce -> decode M=1 atomic) to catch
    # cross-call stale state, and in particular a candidate that leaves a dirty per-slot scratch or
    # a stale route_out buffer behind when the two paths alternate.
    order = [c.get("sig") for c in (META.get("call_sequence") or [])]
    by_sig = {r["sig"]: r for r in recs}
    ordered = [{"args": by_sig[s]["args"], "ref": by_sig[s]["ref"], "sig": s}
               for s in order if s in by_sig]
    if ordered:
        s_ok, s_rows = h.check_correct_sequence(cases.call, ordered, TOL)
        ok = ok and s_ok
        for r in s_rows:
            print(f"[correctness/sequence] {r['case'][:70]}: "
                  f"{'PASS' if r.get('correct') else 'FAIL'} err={r.get('max_rel_err')}")

    print(f"CORRECTNESS: {'PASS' if ok else 'FAIL'}")

    # ---------------------------------------------------------------- timing (both legs, per bucket)
    per_case = h.measure_legs(HERE, META)
    for c in per_case:
        print(f"[timing] m={c.get('m')} regime={c.get('regime')} "
              f"baseline_ms={c.get('baseline_ms')} optimized_ms={c.get('optimized_ms')} "
              f"speedup={c.get('speedup')} reps={c.get('reps')} spread={c.get('speedup_spread')}")
    res = h.serving_weighted_speedup(per_case, META)
    print(json.dumps({"per_case": res["per_case"], "included": res["included"],
                      "dropped_unserved": res["dropped_unserved"],
                      "suspect_identity": res["suspect_identity"], "reason": res["reason"]}))
    print(f"GEAK_GEOMEAN_SPEEDUP: {res['geomean']}")
    print(f"GEAK_WEIGHTED_SPEEDUP: {res['weighted']}")
    return 0 if ok else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except h.HarnessIncompleteError:
        sys.exit(3)
