// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_rotary_embedding` namespace so the task
// can call torch.ops.extracted_rotary_embedding.rotary_embedding without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void rotary_embedding( torch::Tensor& positions, torch::Tensor& query, std::optional<torch::Tensor> key, int64_t head_size, torch::Tensor& cos_sin_cache, bool is_neox);

TORCH_LIBRARY(extracted_rotary_embedding, m) {
    m.def("rotary_embedding(Tensor positions, Tensor! query,                 Tensor!? key, int head_size,                 Tensor cos_sin_cache, bool is_neox) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_rotary_embedding, CUDA, m) {
    m.impl("rotary_embedding", &rotary_embedding);
}
