// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_reshape_and_cache` namespace so the task
// can call torch.ops.extracted_reshape_and_cache.reshape_and_cache without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void reshape_and_cache( torch::Tensor& key, torch::Tensor& value, torch::Tensor& key_cache, torch::Tensor& value_cache, torch::Tensor& slot_mapping, const std::string& kv_cache_dtype, torch::Tensor& k_scale, torch::Tensor& v_scale);

TORCH_LIBRARY(extracted_reshape_and_cache, m) {
    m.def("reshape_and_cache(Tensor key, Tensor value,                  Tensor! key_cache, Tensor! value_cache,                  Tensor slot_mapping,                  str kv_cache_dtype,                  Tensor k_scale, Tensor v_scale) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_reshape_and_cache, CUDA, m) {
    m.impl("reshape_and_cache", &reshape_and_cache);
}
