// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_concat_and_cache_mla` namespace so the task
// can call torch.ops.extracted_concat_and_cache_mla.concat_and_cache_mla without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void concat_and_cache_mla( torch::Tensor& kv_c, torch::Tensor& k_pe, torch::Tensor& kv_cache, torch::Tensor& slot_mapping, const std::string& kv_cache_dtype, torch::Tensor& scale);

TORCH_LIBRARY(extracted_concat_and_cache_mla, m) {
    m.def("concat_and_cache_mla(Tensor kv_c, Tensor k_pe,                     Tensor! kv_cache,                     Tensor slot_mapping,                     str kv_cache_dtype,                     Tensor scale) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_concat_and_cache_mla, CUDA, m) {
    m.impl("concat_and_cache_mla", &concat_and_cache_mla);
}
