// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_moe_sum` namespace so the task
// can call torch.ops.extracted_moe_sum.moe_sum without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void moe_sum(torch::Tensor& input, torch::Tensor& output);

TORCH_LIBRARY(extracted_moe_sum, m) {
    m.def("moe_sum(Tensor input, Tensor! output) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_moe_sum, CUDA, m) {
    m.impl("moe_sum", &moe_sum);
}
