// Auto-generated by extractor.source.hip_extractor.
// Re-registers the extracted op into the `extracted_silu_and_mul` namespace so the task
// can call torch.ops.extracted_silu_and_mul.silu_and_mul without touching the host engine.
#include <torch/library.h>
#include <torch/torch.h>

void silu_and_mul(torch::Tensor& out, torch::Tensor& input);

TORCH_LIBRARY(extracted_silu_and_mul, m) {
    m.def("silu_and_mul(Tensor! result, Tensor input) -> ()");
}

TORCH_LIBRARY_IMPL(extracted_silu_and_mul, CUDA, m) {
    m.impl("silu_and_mul", &silu_and_mul);
}
